from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent

DATA_DIR = BASE_DIR / "data"
DATABASE_PATH = DATA_DIR / "app.db"
RAW_DOCUMENTS_DIR = DATA_DIR / "raw_documents"
RAW_DOCUMENTS_CITIZENS_DIR = RAW_DOCUMENTS_DIR / "citizens"
RAW_CSV_DIR = DATA_DIR / "raw_csv"
SNAPSHOTS_DIR = DATA_DIR / "snapshots"
EXPORTS_DIR = DATA_DIR / "exports"

CHROME_PROFILES_DIR = BASE_DIR / "chrome_profiles"
CITIZENS_PROFILE_NAME = "citizens"
CITIZENS_PROFILE_PATH = CHROME_PROFILES_DIR / CITIZENS_PROFILE_NAME
CITIZENS_DOWNLOAD_DIR = RAW_DOCUMENTS_CITIZENS_DIR

SCREENSHOTS_DIR = BASE_DIR / "screenshots"
BACKUPS_DIR = BASE_DIR / "backups"
CITIZENS_CAPTURE_SCREENSHOTS = False

DASHBOARD_STATE_PATH = BASE_DIR / "dashboard_state.json"
LAST_RESULT_PATH = BASE_DIR / "last_result.json"
AUDIT_LOG_PATH = BASE_DIR / "automation_record_log.txt"
CITIZENS_MFA_CODE_PATH = DATA_DIR / "citizens_mfa_code.json"

APP_NAME = "Financial Dashboard"
APP_HOST = "127.0.0.1"
APP_PORT = 5050
APP_DEBUG = False

CITIZENS_SITE_KEY = "citizens"
CITIZENS_DISPLAY_NAME = "Citizens Checking"
CITIZENS_ACCOUNT_TYPE = "checking"
CITIZENS_LOGIN_URL = "https://www.citizensbankonline.com/olb-root/login"
CITIZENS_HOME_URL = "https://www.citizensbankonline.com/olb-root/home/accounts"
CITIZENS_DOCUMENT_CENTER_URL = "https://www.citizensbankonline.com/olb-root/home/document-center"
CITIZENS_ALL_STATEMENTS_START_DATE = "2020-05-08"
CITIZENS_DEBUGGER_ADDRESS = "127.0.0.1:9222"
CITIZENS_DEBUGGING_PORT = 9222

WORKER_TIMEOUT_SECONDS = 900
DOWNLOAD_TIMEOUT_SECONDS = 45
PAGE_READY_TIMEOUT_SECONDS = 30
SCREENSHOT_FORMAT = "png"

STATUS_IDLE = "idle"
STATUS_RUNNING = "running"
STATUS_WAITING_FOR_LOGIN = "waiting_for_login"
STATUS_WAITING_FOR_MFA = "waiting_for_mfa"
STATUS_WAITING_FOR_USER_ACTION = "waiting_for_user_action"
STATUS_SUCCESS = "success"
STATUS_FAILED = "failed"
STATUS_CANCELLED = "cancelled"

REQUIRED_DIRECTORIES = [
    DATA_DIR,
    RAW_DOCUMENTS_DIR,
    RAW_DOCUMENTS_CITIZENS_DIR,
    RAW_CSV_DIR,
    SNAPSHOTS_DIR,
    EXPORTS_DIR,
    CHROME_PROFILES_DIR,
    CITIZENS_PROFILE_PATH,
    SCREENSHOTS_DIR,
    BACKUPS_DIR,
]
